### PR TITLE
Add support for MSIX file extensions & downlevel OS

### PR DESCRIPTION
**Pull request by onovotny**

### CODE REVIEW

**Comment by vcsjones** [comment]
At this point I'm on board with the chances to AzureSign.Core but "meh" on the tool.

1. I think this would preclude us from ever distributing a NuGet global tool package of the CLI since it looks like we'd have to redistribute part of the Windows SDK in order to get these libraries in the right place when the global tool gets installed.
2. Presumably this would work without the changes on RS5 which I personally have no reservations with saying "MSIX signing requires RS5 or Server 2019". Now I know that doesn't help the case of Server 2016 app services, but you have your own process host anyway that needs to do the same things.

It would be cool if this did work. Is it possible to change the csproj so that if the SDK is not present that it fail gracefully and not copy anything?

1. The global tool would ship with no SDK parts and would work on RS5. I could add some smarts to detect if the APPX SIP will handle MSIX and give a friendly error message.
2. If someone does want it to work on pre-RS5 or Server 2016, all they have to do is build from source and make sure they have an SDK installed.

**Comment by onovotny** [comment]
Stay tuned re the redist issue.

**Comment by vcsjones** [comment]
@onovotny Any chance we can split this PR to be just the AzureSign.Core part? I'll have time over the holiday weekend to push up package to NuGet and it'd be cool to get that in there.

**Comment by onovotny** [comment]
Yes, been traveling the past few days, I'll see if I can do this on Friday.

**Comment by onovotny** [comment]
@vcsjones Here's a PR with just the first commit for file extensions https://github.com/vcsjones/AzureSignTool/pull/52

**Comment by onovotny** [comment]
What could make this better, is to use the activation contexts programmatically so that we can include the x86 and x64 native files alongside and import them dynamically based on the installed architecture. Then, the normal `PackAsTool` should work fine and the manifest does not need to be embedded in the exe.

**Comment by vcsjones** [comment]
(FYI I am working on this for the Console tool with contexts to see if I can get it working with x64 and x86).

**Pull request closed without merging**
