### PR TITLE
Appx support

### LINKED ISSUE #2: Appx/AppxBundle support
Might be worth spelling out what's required for appx/appxbundles. I think files from the Windows SDK directory need to be in the same directory (possibly the wintrust.dll/wintrust.dll.ini) as this tool along with some of the Opc dll's. I know it needs some of the exe's in there too.

I can play with this later this week.

### PR DESCRIPTION
**Pull request by vcsjones**
Fixes #2 and #3.

### CODE REVIEW

**Comment by onovotny** [comment]
With these changes, I assume that there's no need for local copies of any dlls? For appxbundle, I believe it needs makeappx/makepri available since it shells out to them. Will test.

**Comment by onovotny** [comment]
Nm, I'm thinking of Makeappx that needs makepri if you bundle.

**Comment by vcsjones** [comment]
What ended up being the answer to native component requirements?

**Comment by onovotny** [comment]
AzureSignTool alone doesn't have any. If you want to unpack/pack appx's to strip the signature and modify the values, you need:

-	Appxpackaging.dll
-	MakeAppx.exe
-	MakePri.exe
-	Microsoft.Windows.Build.Appx.AppxPackaging.dll.manifest
-	Microsoft.Windows.Build.Appx.OpcServices.dll.manifest
-	OpcServices.dll

**Comment by vcsjones** [comment]
Excellent. I tested CAB, MSI, APPX, EXE / DLL (anything PE). I wasn't sure how to test eappx or appxbundle.

**Comment by onovotny** [comment]
appxbundle is harder since it requires a bundle to start plus changing the appxmanifest inside the contained appx. I did test it with the sign service and it worked. 

The gist is this -- create an appxbundle in Visual Studio with the publish uwp option.

Use the makeappx commands to unbundle to a temp dir. that'll have one or more appx files. For each of those, run makeappx command to unpack each of those to a different temp dir. Edit the appxmanifest to ensure the publisher identity matches the subject. Then reverse the process. makeappx pack each of the extracted appx's overwriting the original ones in the bundle's temp dir. Then makeappx bundle to rebundle.

Then you can use that unsigned bundle, with the correct subject names in the manifests, as a parameter to SignerSignEx3.

**Comment by vcsjones** [comment]
Zoinks. I'll take your word for it.

**Comment by onovotny** [comment]
Yeah, a task well-suited for automation

**Pull request merged**
